name: Linting

on: [push, pull_request]

jobs:
  continuous_integration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 12.x

      - run: npm install
      - run: npm run css-lint
